import { Link } from 'react-router-dom';
import Navbar from '../components/Navbar';
import Footer from '../components/Footer';
import styles from './LandingPage.module.css';

const stats = [
  { value: '50K+', label: 'Articles published daily' },
  { value: '16+',  label: 'Newspaper sources' },
  { value: '2M+',  label: 'Active readers' },
  { value: '4.9',  label: 'Average reader rating' },
];

const featuresTop = [
  {
    icon: '🤖',
    title: 'AI-powered briefings',
    desc: 'Morning summaries tailored to your interests, automatically generated by AI — delivered before you wake up.',
  },
  {
    icon: '🌍',
    title: 'Global coverage',
    desc: 'Reporters on the ground in Algeria and newspapers in 16 countries tell the stories as they happen, from verified, trusted sources.',
  },
  {
    icon: '🔔',
    title: 'Real-time alerts',
    desc: 'Be first to know about the stories that matter to you — not the noise, not the fluff, hours later.',
  },
];

const featuresBottom = [
  {
    icon: '🔖',
    title: 'Save & annotate',
    desc: 'Bookmark articles, add private notes and build your personal reading archive — accessible on any device.',
  },
  {
    icon: '📑',
    title: 'Save & annotate',
    desc: 'Bookmark more articles, add private notes and build your personal reading archive — accessible on any device.',
  },
];

const steps = [
  { num: 1, title: 'Sign Up',  desc: 'Create your account to join millions of readers with basic information.' },
  { num: 2, title: 'Your Up',  desc: 'Create your account to join millions of readers with basic information.' },
  { num: 3, title: 'Sign Up',  desc: 'Create your account just a few minutes with basic information.' },
];

export default function LandingPage() {
  return (
    <div className={styles.page}>

      {/* ── NAVBAR ── */}
      <Navbar />

      {/* ── HERO ── */}
      {/* The entire hero section has the lavender radial gradient as its background */}
      <section className={styles.hero} id="features">
        <div className={styles.heroContent}>
          <h1 className={styles.heroTitle}>
            The world's stories,<br />
            <span className={styles.heroAccent}>curated for you.</span>
          </h1>
          <p className={styles.heroDesc}>
            News Dispatch delivers personalized journalism across business, tech,
            sport and politics — powered by editorial intelligence, not just algorithms.
          </p>
          <div className={styles.heroBtns}>
            <Link to="/dashboard" className={styles.btnPrimary}>Start discovering →</Link>
            <Link to="/login"     className={styles.btnGhost}>I have already an account</Link>
          </div>
        </div>

        {/* Stats bar — sits at the bottom of the hero, overlapping into the white below */}
        <div className={styles.statsBar}>
          {stats.map((s) => (
            <div key={s.label} className={styles.statItem}>
              <span className={styles.statValue}>{s.value}</span>
              <span className={styles.statLabel}>{s.label}</span>
            </div>
          ))}
        </div>
      </section>

      {/* ── FEATURES ── */}
      <section className={styles.featuresSection}>
        <div className={styles.featuresTopRow}>
          {featuresTop.map((f) => (
            <div key={f.title + f.icon} className={styles.featureCard}>
              <div className={styles.featureIconWrap}>{f.icon}</div>
              <h3 className={styles.featureTitle}>{f.title}</h3>
              <p className={styles.featureDesc}>{f.desc}</p>
            </div>
          ))}
        </div>
        <div className={styles.featuresBottomRow}>
          {featuresBottom.map((f) => (
            <div key={f.title + f.icon} className={styles.featureCard}>
              <div className={styles.featureIconWrap}>{f.icon}</div>
              <h3 className={styles.featureTitle}>{f.title}</h3>
              <p className={styles.featureDesc}>{f.desc}</p>
            </div>
          ))}
        </div>
      </section>

      {/* ── HOW IT WORKS ── */}
      <section className={styles.howSection} id="how-it-works">
        <h2 className={styles.sectionTitle}>How it works</h2>
        <div className={styles.steps}>
          {steps.map((s) => (
            <div key={s.num} className={styles.step}>
              <div className={styles.stepNum}>{s.num}</div>
              <h4 className={styles.stepTitle}>{s.title}</h4>
              <p className={styles.stepDesc}>{s.desc}</p>
            </div>
          ))}
        </div>
      </section>

      {/* ── CTA BANNER ── */}
      <section className={styles.ctaSection}>
        <div className={styles.ctaBanner}>
          <h2 className={styles.ctaTitle}>Ready to stay informed?</h2>
          <p className={styles.ctaDesc}>
            Join our community of readers who start their day with News Dispatch.
          </p>
          <Link to="/signup" className={styles.ctaBannerBtn}>Create your free account →</Link>
        </div>
      </section>

      <Footer />
    </div>
  );
}
